lang: en-US
title: Aleksandr Piatkin
description: >
    Hello there!
    My name is Aleksandr Piatkin.
    I come from Samara, Russia and reside in Berlin, Germany.
    I work as a software engineer at heycar.
baseurl: ""
url: "https://aptkn.ch"
github_username:  aspyatkin

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

timezone: Europe/Berlin

author: aptkn

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - script
  - logs

include:
  - .ssh
  # - .gpg
